# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab07d04daa2fc78b62aeae28631fa1012e0f94292f1cb3a2e0d11ab85d3e702cce47e2b3f18f4fb9934f01dfb4704ef346c5149b9d9f60c608c8ce8e09f0b054

test:
  secret_key_base: 0ac0df2df34b2b6706048dd1456ed08703f74c25b3018a9218551a26f28b84a5512cfde6bae4278662e1968417c47139ff4efb08ffa79d852149494232a72b14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
